

database:
  path: "database.db"
  drop_db: false

files:
  basedir_enroll_path: "./registered_faces"

frame_controller:
  max_queue_size: null
  sources:
    - id: 0
      source: 0
      name: 'webcam'
      device: "cpu"
      yolo: "yolo11n.pt"
      fps: 30
      timeout: 0.1
      scale_size: 100
      face_recogniser_threshold: 0.5
      motion_detector_threshold: 0.5
      motion_detector_min_area: 500
      motion_detector: "mog2" # mog2 or optical_flow
      view: true

    - id: 1
      source: 'datasets/WiseNET/set_1/video1_1.avi'
      name: 'camera_1_set_5'
      device: "cpu"
      yolo: "yolo11n.pt"
      fps: 30
      timeout: 0.1
      scale_size: 100
      face_recogniser_threshold: 0.5
      motion_detector_threshold: 0.5
      motion_detector_min_area: 500
      motion_detector: "mog2" # mog2 or optical_flow
      view: true

    - id: 2
      source: 'datasets/WiseNET/set_1/video1_2.avi'
      name: 'camera_2_set_5'
      device: "cpu"
      yolo: "yolo11n.pt"
      fps: 30
      timeout: 0.1
      scale_size: 100
      face_recogniser_threshold: 0.5
      motion_detector_threshold: 0.5
      motion_detector_min_area: 500
      motion_detector: "mog2" # mog2 or optical_flow
      view: true
logger:
    level: "DEBUG"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    to_file: false
    file_path: "log.log"


# example of a configuration file
#database:
#  path: "database.db"
#  drop_db: false
#
#files:
#  basedir_enroll_path: "./registered_faces"
#
#frame_controller:
#  sources: [0, 1, "path_to_video.mp4"]
#  yolo_model_name: "yolo11n.pt"
#  max_queue_size: null     # equivalenti a None in Python
#  fps: 30
#  timeout: 0.1
#  scale_size: 100
#  view: true
#  device: "cpu"
#  face_recogniser_threshold: 0.5
#
#logger:
#    level: "INFO"
#    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
#    datefmt: "%Y-%m-%d %H:%M:%S"
#    to_file: false
#    file_path: "log.log"